### ISSUE TITLE
Configuration confusion on service names

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clara-java#13]
I think that If the YAML name of a service is wholly contained in the name of another service, there's configuration issues.  I remember thinking we saw this years ago and never got it addressed, but instead just changed names, and I think we hit it again now.  Here's the relevant subset of an example YAML that gives issues:

```
services:
  - class: org.jlab.jnp.grapes.services.JpsiTcsWagon
    name: JPSITCS
  - class: org.jlab.jnp.grapes.services.FTJpsiWagon
    name: JPSI
```

And the resulting runtime errors:

```
2023-06-24 20:31:34: UNHANDLED EXCEPTION ON SERVICE EXECUTION: 129.57.139.19%7880_java:clas12-2:JPSI
java.lang.NullPointerException
	at org.jlab.clara.sys.ServiceEngine.parseComposition(ServiceEngine.java:203)
	at org.jlab.clara.sys.ServiceEngine.execute(ServiceEngine.java:152)
	at org.jlab.clara.sys.Service.lambda$execute$2(Service.java:178)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Will confirm shortly whether expanding the latter's name to "JPSIFOOBAR", for example, addresses the behavior.  If so, might be consistent with a String.contains() when maybe ought to be a String.equals().

**Comment by gurjyan** [comment]
Working on it.

**Comment by baltzell** [comment]
Yes, I confirmed just changing the name JPSI->JPSISTUFF in the example above makes the issue go away.

**Comment by gurjyan** [comment]
The validation procedure is designed to identify potential conflicts within the service names as designated by the user within the YAML configuration file. These names must comply with the CLARA service composition specifications, which are predominantly governed by the naming conventions employed in the ZeroMQ publisher-subscriber messaging protocol. As per the established criteria, redundancy in service names is prohibited, and no service name can serve as a prefix for another service name. For instance, the service names "abc" and "abcFred" would be deemed conflicting according to these rules. In the most recent iteration of the codebase, any detection of such conflicts will result in the triggering of an exception.

**Comment by baltzell** [comment]
Thanks!  A more obvious exception is better.
